version: '2'
services:
  webapi:
    build: ./artifacts/VSS.Productivity3D.Scheduler.WebApi
    env_file:
     - docker-compose-local.env
    volumes:
      - ./artifacts/logs:/app/logs
    ports:
     - "3001:80"
    depends_on:
      - schema
      - projectschema
      - db
      - dbmssql
      - schemamssql
  mockprojectwebapi:
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-mockproject-webapi:latest-linux
    env_file:
     - docker-compose-local.env
    ports:
     - "5001:5001"
  projectschema:
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:latest
    env_file:
     - docker-compose-local.env
    environment:
     - MYSQL_DATABASE_NAME=VSS-Productivity3D-Project
    depends_on:
      - db      
  schema:
    build: ./database
    env_file:
     - docker-compose-local.env
    environment:
     - MYSQL_SERVER_NAME=db
     - MYSQL_DATABASE_NAME=VSS-Productivity3D-Scheduler
     - MYSQL_PORT=3306
     - MYSQL_USERNAME=root
     - MYSQL_ROOT_PASSWORD=abc123
    depends_on:
     - db
  db:
    image: mysql/mysql-server:5.7.15
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    env_file:
     - docker-compose-local.env
    ports:
      - "3306:3306"
  schemamssql:
    build: ./databaseMsSql
    env_file:
     - docker-compose-local.env
    environment:
     - MSSQL_SERVER_NAME=dbmssql
     - MSSQL_DATABASE_NAME=NH_OP
     - MSSQL_PORT=1433
     - MSSQL_USERNAME=sa
     - MSSQL_ROOT_PASSWORD=d3vRDS1234_
    depends_on:
     - dbmssql
  dbmssql:
    image: microsoft/mssql-server-linux:latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=d3vRDS1234_
    env_file:
     - docker-compose-local.env
    ports:
      - "1433:1433"
  accepttest:
    build: ./AcceptanceTests/deploy
    env_file:
     - docker-compose-local.env
    volumes:
      - ./AcceptanceTests/deploy/testresults:/app/testresults
    depends_on:
      - webapi