kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag | lower }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag | lower }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
