kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "trex.name" . }}-clusterrole
  labels:
    app: {{ template "trex.deployname" . }}
    chart: {{ template "trex.chart" . }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["endpoints"]
  verbs: ["get"]
