# An example of a Kubernetes configuration for Ignite pods deployment.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "trex.fullname" . }}-{{ .Values.environment }}-mds
  labels:
    app: {{ template "trex.deployname" . }}
    chart: {{ template "trex.chart" . }}
    component: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag }}-mds
spec:
  selector:
    matchLabels:
      #this must match one of metadata.labels above
      component: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag }}-mds
  # A number of Ignite pods to be started by Kubernetes initially.
  replicas: {{ .Values.mutableData.replicaCount }}
  template:
    metadata:
      labels:
        # This label has to be added to the selector's section of 
        # ignite-service.yaml so that the Kubernetes Ignite lookup service
        # can easily track all Ignite pods available deployed so far.
        app: {{ template "trex.deployname" . }}
        component: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag }}-mds
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ .Values.serviceAccountName }}
      
      containers:
        # Custom Ignite pod name.
      - name: ignite-node
        # Ignite Docker image. Kubernetes IP finder is supported starting from
        # Apache Ignite 2.3.0
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}.MutableData
        
        resources:
{{ toYaml .Values.mutableData.resources | indent 10 }}

        command: ["dotnet"]
        args: ["VSS.TRex.Server.MutableData.dll"]

        env:
        - name: IGNITE_HOME
          value: "/trex/"
        - name: ENABLE_TFA_SERVICE
          value: {{ .Values.mutableData.environment.enableTfa | quote }}
        - name: TFA_PROJECTV2_API_URL
          value: {{ .Values.mutableData.environment.tfaProjectV2ApiUrl }}
        - name: IS_KUBERNETES
          value: "true"
        - name: DEPLOYED_ENV
          value: {{ .Values.environment }}
        - name: ENABLE_TAGFILE_ARCHIVING
          value: {{ .Values.mutableData.environment.enableTagFileArchiving | quote }}
        - name: ENABLE_TAGFILE_ARCHIVING_METADATA
          value: {{ .Values.mutableData.environment.enableTagFileArchivingMetadata | quote }}
        - name: MIN_TAGFile_LENGTH
          value: {{ .Values.mutableData.environment.minTagFileLength | quote }}
        - name: TAGFILE_ARCHIVE_FOLDER
          value: {{ .Values.mutableData.environment.tagfileArchiveFolder }}


        ports:
        # Ports to open.
        - containerPort: 47100 # communication SPI port number.
          name: spicoms
        - containerPort: 47500 # discovery SPI port number.
          name: spidisco
        - containerPort: 48100 # communication SPI port number.
          name: spicommsmutable
        - containerPort: 48500
          name: spidiscomutable
        - containerPort: 49112 # JMX port number.
          name: jmx
        - containerPort: 8080  # REST port number.
          name: restapi
        - containerPort: 10800 # SQL port number.
          name: sql

        volumeMounts:
        # Mounting the persistant storage - currently this is in temp which will change when we sort config
        - mountPath: "/persist/"
          name: trex-mutable-storage

  volumeClaimTemplates:
  - metadata:
      name: trex-mutable-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.mutableData.storageSize }}