apiVersion: v1
kind: ConfigMap
metadata:
  name: 3dapp-alpha
  namespace: alpha
data: 
# Kubernetes Cluster Info - This must match the namespace (including case) that the pods will run in
  kubernetesNamespace: alpha
# TCC configuration
  TCCBASEURL: https://www.myconnectedsite.com
  TCCFILESPACEID: ua9bc5eaf-583a-44d3-b33b-24c035946ae2
  TCC_TAGFILE_FILESPACEID: u5c9bf2ff-7a5a-4cdf-86aa-3753f120eef2
#Jaeger configuration
#  JAEGER_AGENT_HOST: jaeger-agent.logging
#  JAEGER_AGENT_PORT: "6831"
#  JAEGER_SAMPLER_TYPE: const
#MySql configuration
  MYSQL_SERVER_NAME_VSPDB: rds-rpd-mydb04.cfyg2f3omhgy.us-west-2.rds.amazonaws.com
  MYSQL_PORT: "3306"
#Service references  
  cws_profilemanager_public_v1: https://api-stg.trimble.com/t/trimble.com/cws-profilemanager-stg/1.0
  PREFERENCE_API_URL: https://api-stg.trimble.com/t/trimble.com/ccss-3d-alpha-preferenceservice/1.0
  VETA_EXPORT_URL: https://api-stg.trimble.com/t/trimble.com/ccss-3d-alpha-productivity/1.0/export/veta
  TILE_INTERNAL_BASE_URL: http://tile.alpha.eks.ccss.cloud/internal/v1
#SERVICE DISCOVERY REFERENCES
  assetdetails_public_v1: https://alpha1ufl.myvisionlink.com/t/trimble.com/ccss-3d-alpha-UnifiedFleet/1.0
  assetsummary_public_v1: https://alpha1ufl.myvisionlink.com/t/trimble.com/ccss-3d-alpha-assetutilization/1.1 
  productivity3d_service_public_v1: https://api-stg.trimble.com/t/trimble.com/ccss-3d-alpha-productivity/1.0
  productivity3d_service_public_v2: https://api-stg.trimble.com/t/trimble.com/ccss-3d-alpha-productivity/1.0
  cws_profilemanager_public_v1: https://api-stg.trimble.com/t/trimble.com/cws-profilemanager-stg/1.0
  cws_devicemanager_public_v2: https://api-stg.trimble.com/t/trimble.com/cws-devicemanager-stg/2.0
  TPAAS_OAUTH_URL: https://identity-stg.trimble.com/i/oauth2
#Misc stuff
  TILE_RENDER_MAX_ZOOM_LEVEL: "21"
  TILE_RENDER_MAX_ZOOM_RANGE: "14"
  TILE_RENDER_WAIT_INTERVAL: "2000"
  LOG_MAX_CHAR: "1000"
  SCHEDULER_FILTER_CLEANUP_TASK_AGE_MINUTES: "720"
  DOWNLOAD_FOLDER: C:/temp/
  ALK_KEY: 97CC5BD1CA28934796791B229AE9C3FA
  ALK_BASE_URL: http://pcmiler.alk.com/APIs/REST/v1.0/Service.svc
  AWS_TAGFILE_BUCKET_NAME: ccss-tag-file-archive
  ENVIRONMENT: ALPHA
  CORECLR_ENABLE_PROFILING: "0"
#AWS configuration  
  AWS_BUCKET_NAME: ccss-exports-stg
  AWS_PRESIGNED_URL_EXPIRY: 7.00:00:00
#Raptor configuration
  ASNODEIP: 10.97.96.150
  ENABLE_CONNECTED_SITE_GATEWAY: "false"
  ENABLE_RAPTOR_GATEWAY_DESIGNIMPORT: "true"
  ENABLE_RAPTOR_GATEWAY_TAGFILE: "false"
  ENABLE_TREX_GATEWAY_CCA_PALETTE: "false"
  ENABLE_TREX_GATEWAY_CELL_DATUM: "false"
  ENABLE_TREX_GATEWAY_DESIGNIMPORT: "false"
  ENABLE_TREX_GATEWAY_EDIT_DATA: "false"  
  ENABLE_TREX_GATEWAY_ELEVATION: "false"
  ENABLE_TREX_GATEWAY_EXPORT_PASSCOUNT: "false"
  ENABLE_TREX_GATEWAY_GRIDREPORT: "false"
  ENABLE_TREX_GATEWAY_LINEWORKFILE: "false"
  ENABLE_TREX_GATEWAY_PROJECTSTATISTICS: "false"
  ENABLE_TREX_GATEWAY_STATIONOFFSET: "false"
  ENABLE_TREX_GATEWAY_SURFACE: "false"
  ENABLE_TREX_GATEWAY_TAGFILE: "false"
  ENABLE_TREX_GATEWAY_TILES: "false"
  ENABLE_TREX_GATEWAY_VETA: "false"
  IONODEIP: 10.97.96.165
  RAPTORUSERNAME: svcRaptor
  SHAREUNC: \\alpha-iolv01.vssengg.com\ProductionData
  TCCSynchOtherIssueFolder: Other... (Issue)
  TCCSynchProductionDataArchivedFolder: Production-Data (Archived)
  TCCSynchProjectBoundaryIssueFolder: Project Boundary (Issue)
  TCCSynchSubscriptionIssueFolder: Subscription (Issue)
#Cache
  MAX_FILE_SIZE: "100000000"
  TILE_CACHE_LIFE: 00:15:00
  CUSTOMER_CACHE_LIFE: 00:30:00
  CWS_CACHE_LIFE: 00:30:00
  ELEVATION_EXTENTS_CACHE_LIFE: 00:30:00
  FILTER_CACHE_LIFE: 00:15:00
  IMPORTED_FILE_CACHE_LIFE: 00:15:00
  PROJECT_CACHE_LIFE: 00:30:00
  ASSETMGMT_CACHE_LIFE: 00:30:00
  PROJECT_SETTINGS_CACHE_LIFE: 00:15:00
  TILE_RENDER_JOB_TIMEOUT: 00:00:10  
  DEFAULT_CONNECTION_LIMIT: "64"
  LIBUV_THREAD_COUNT: "32"
  MAX_IO_THREADS: "1024"
  MAX_WORKER_THREADS: "512"
  MIN_IO_THREADS: "1024"
  MIN_WORKER_THREADS: "512"
  SCHEDULED_JOB_TIMEOUT: "900000"
#Notifications
  NOTIFICATION_HUB_URL: http://push.alpha.eks.ccss.cloud/notifications
  PUSH_NO_AUTHENTICATION_HEADER: "true" 
#DataOcean
  DATA_OCEAN_URL: https://api-stg-usw2.trimblepaas.com/data_ocean_stage-v1.0
  DATA_OCEAN_UPLOAD_TIMEOUT_MINS: "5"
  DATA_OCEAN_UPLOAD_WAIT_MILLSECS: "1000"
  DATA_OCEAN_ROOT_FOLDER_ID: 3e415c56-2690-4e38-a36b-8ff1ee489f89
  ENABLE_DATA_OCEAN: "true"
#Pegasus
  PEGASUS_DXF_PROCEDURE_ID: 1d05aebc-37b7-4c90-8c6c-ba5d0d1c9290
  PEGASUS_GEOTIFF_PROCEDURE_ID: f61c965b-0828-40b6-8980-26c7ee164566
  PEGASUS_EXECUTION_TIMEOUT_MINS: "30"
  PEGASUS_EXECUTION_WAIT_MILLSECS: "20000"
  PEGASUS_URL: https://api-stg-usw2.trimblepaas.com/pegasus_stage-v1.0
  SCHEDULER_ENABLE_DXF_TILE_GENERATION: "true"

