version: '3'
services:
  webapi_alpha:
    image: 300213723870.dkr.ecr.us-west-2.amazonaws.com/vss-raptor-webapi:[VERSION]
    restart: always
    deploy:
      replicas: 1
    environment:
     - ALK_KEY=97CC5BD1CA28934796791B229AE9C3FA
     - ASNODEIP=10.97.96.150
     - assetmgmt3d_service=http://assetmgmt3d.alpha.eks.vspengg.com
     - push_service=http://push.alpha.eks.vspengg.com
     - scheduler_service=http://scheduler.alpha.eks.vspengg.com
     - project_service=http://project.alpha.eks.vspengg.com
     - filter_service=http://filter.alpha.eks.vspengg.com
     - tagfileauth_service=http://tagfileauth.alpha.eks.vspengg.com
     - trex_service_connectedsite=http://connectedsite.alpha.eks.vspengg.com
     - trex_service_immutable=http://trex.immutable.dev.eks.vspengg.com
     - trex_service_mutable=http://trex.mutable.dev.eks.vspengg.com
     - ASSETMGMT_CACHE_LIFE=00:15:00
     - AWS_DESIGNIMPORT_BUCKET_NAME=vss-project3dp-stg
     - AWS_PRESIGNED_URL_EXPIRY=7.00:00:00
     - AWS_TAGFILE_BUCKET_NAME=vss-stg-directtagfile-archives
     - CUSTOMERSERVICE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-alpha-customerservice/1.0/Customers/me
     - CUSTOMER_CACHE_LIFE=00:30:00
     - DEFAULT_CONNECTION_LIMIT=64
     - ELEVATION_EXTENTS_CACHE_LIFE=00:15:00
     - ENABLE_CONNECTED_SITE_GATEWAY=true
     - ENABLE_RAPTOR_GATEWAY_TAGFILE=true
     - ENABLE_TREX_GATEWAY_CELL_DATUM=false
     - ENABLE_TREX_GATEWAY_DESIGNIMPORT=false
     - ENABLE_TREX_GATEWAY_ELEVATION=false
     - ENABLE_TREX_GATEWAY_EXPORT_PASSCOUNT=false
     - ENABLE_TREX_GATEWAY_GRIDREPORT=false
     - ENABLE_TREX_GATEWAY_LAYERS=false
     - ENABLE_TREX_GATEWAY_LINEWORKFILE=false
     - ENABLE_TREX_GATEWAY_MACHINEDESIGNS=false
     - ENABLE_TREX_GATEWAY_MACHINES=false
     - ENABLE_TREX_GATEWAY_PROJECTSTATISTICS=false
     - ENABLE_TREX_GATEWAY_STATIONOFFSET=false
     - ENABLE_TREX_GATEWAY_SURFACE=false
     - ENABLE_TREX_GATEWAY_TAGFILE=false
     - ENABLE_TREX_GATEWAY_TILES=false
     - ENABLE_TREX_GATEWAY_VETA=false
     - FILTER_CACHE_LIFE=00:15:00
     - GEOFENCE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-alpha-geofenceservice/1.0
     - GEOFENCE_CACHE_LIFE=00:15:00
     - IMPORTED_FILE_CACHE_LIFE=00:15:00
     - IONODEIP=10.97.97.49
     - KAFKA_CAP_GROUP_NAME=3dpm-CAP,
     - KAFKA_PORT=9092
     - KAFKA_TOPIC_NAME_SUFFIX=-Alpha
     - KAFKA_URI=10.97.97.32
     - LIBUV_THREAD_COUNT=32
     - LOG_MAX_CHAR=1000
     - MAX_IO_THREADS=1024
     - MAX_WORKER_THREADS=512
     - MIN_IO_THREADS=1024
     - MIN_WORKER_THREADS=512
     - MYSQL_CAP_DATABASE_NAME=VSS-Productivity3D-CAP-Alpha
     - MYSQL_CAP_TABLE_PREFIX=3dpm
     - MYSQL_PASSWORD_BUILD="V$$8u1ld45er"
     - MYSQL_PORT=3306
     - MYSQL_ROOT_PASSWORD="R58Kper%5"
     - MYSQL_SERVER_NAME_VSPDB=rdsmysql-8469.c31ahitxrkg7.us-west-2.rds.amazonaws.com
     - MYSQL_USERNAME=Merino
     - MYSQL_USERNAME_BUILD="vssBuildUsr"
     - NOTIFICATION_HUB_URL=http://push.alpha.eks.vspengg.com/notifications
     - PREFERENCE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-alpha-preferenceservice/1.0
     - PROJECT_CACHE_LIFE=00:15:00
     - PROJECT_SETTINGS_CACHE_LIFE=00:15:00
     - PUSH_NO_AUTHENTICATION_HEADER=true
     - SCHEDULED_JOB_TIMEOUT=900000
     - SHAREUNC=\\alpha-iolv01.vssengg.com\ProductionData
     - SNAKEPIT_HOST=snakepit.dev.eks.vspengg.com
     - TCCBASEURL=https://www.myconnectedsite.com
     - TCCFILESPACEID=ua9bc5eaf-583a-44d3-b33b-24c035946ae2
     - TCC_TAGFILE_FILESPACEID=u5c9bf2ff-7a5a-4cdf-86aa-3753f120eef2
     - TCCFILESPACENAME=Vldatastore-beta
     - TCCORG=vlbeta
     - TCCPWD=vlbeta_key8
     - TCCSynchOtherIssueFolder=Other... (Issue)
     - TCCSynchProductionDataArchivedFolder=Production-Data (Archived)
     - TCCSynchProjectBoundaryIssueFolder=Project Boundary (Issue)
     - TCCSynchSubscriptionIssueFolder=Subscription (Issue)
     - TCCUSERNAME=vlbeta
     - TILE_BASE_URL=https://api-stg.trimble.com/t/trimble.com/vss-alpha-tile/1.0
     - TILE_RENDER_JOB_TIMEOUT=00:02:00
     - TILE_RENDER_MAX_ZOOM_LEVEL=21
     - TILE_RENDER_MAX_ZOOM_RANGE=14
     - TILE_RENDER_WAIT_INTERVAL=5000    
    ports:
      - "4001:80"
networks:
  default:
    external:
      name: nat