version: '2'
services:
  webapi:
    build: ./artifacts/VSS.Productivity3D.Filter.WebApi
    env_file:
     - docker-compose.env
    volumes:
      - ./artifacts/logs:/app/logs 
    depends_on:
      - schema
  mockprojectwebapi:
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-mockproject-webapi:latest-linux
    env_file:
     - docker-compose.env 
  schema:
    build: ./database 
    env_file:
     - docker-compose.env
    depends_on:
     - db  
  db:
    image: mysql/mysql-server:5.7.15 
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci] 
    env_file:
     - docker-compose.env
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    env_file:
     - docker-compose.env
    environment:
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_CREATE_TOPICS=VSS.Interfaces.Events.MasterData.IFilterEvent:1:1
     - KAFKA_ADVERTISED_PORT=9092
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - zookeeper
  accepttest:
    build: ./AcceptanceTests/deploy
    env_file:
     - docker-compose.env
    volumes:
      - ./AcceptanceTests/deploy/testresults:/app/testresults
    depends_on:
      - webapi      
      - kafka