# Default values for projectservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: dev

rootDomain: k8s.vspengg.com

replicaCount: 1

image:
  repository: "276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-tile-webapi"
  tag: latest

resources:
  limits:
   cpu: 1000m

  requests:
   cpu: 250m
   memory: 256Mi

tolerations: []

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - tile
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: endpoints.k8s.vspengg.com
